name: movies_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.13.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.8
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  flutter_bloc: ^9.1.1
  google_sign_in: ^7.2.0
  equatable: ^2.1.0
  http: ^1.2.2
  cloud_firestore: ^6.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/
  - assets/icons/
  - assets/translation/
  - assets/Images/
  - assets/avatar/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf