// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDigCnTh_0U_GIuX7VClYlqfilB7Py0yAA',
    appId: '1:448824278749:web:f1110226362df218a26534',
    messagingSenderId: '448824278749',
    projectId: 'movie-app-9f75b',
    authDomain: 'movie-app-9f75b.firebaseapp.com',
    storageBucket: 'movie-app-9f75b.firebasestorage.app',
    measurementId: 'G-DMVDVEVJ2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyf1zg3Z-mRiFtrWW2b__aW1qPxdeaN44',
    appId: '1:448824278749:android:456bdb3492bb1bb1a26534',
    messagingSenderId: '448824278749',
    projectId: 'movie-app-9f75b',
    storageBucket: 'movie-app-9f75b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvl0hb5X2nljrHv-Q_K5Vw748PFykWs1g',
    appId: '1:448824278749:ios:f7b760ddc172e22ba26534',
    messagingSenderId: '448824278749',
    projectId: 'movie-app-9f75b',
    storageBucket: 'movie-app-9f75b.firebasestorage.app',
    iosClientId: '448824278749-arp95takr263fs785b0t7m1gui4bsuen.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
